### ISSUE TITLE
Doesn't work with acf 5.3.5

### ISSUE THREAD

**Issue by dan-andreoli** [morganleek/acf-wc-product-type-locations#3]
I've tried this plugin, and it seems not working at all with my version of ACF
there is any hack to get it work?

Thanks,

Daniele

**Comment by morganleek** [comment]
Daniele,

Thanks for your message. I've not been maintaining the plugin in the last few months. I'll take a look at it today and see if I can quickly resolve the issue.

Are you seeing specific errors or is it just not appearing?

Regards,
Morgan

**Comment by dan-andreoli** [comment]
field group created doesn't appear in the product location specified

**Comment by morganleek** [comment]
It appears there was a rather silly debugging function left in there that I suspect was causing the issue. It is working on my test repo, can you let me know how you go?
